#! /bin/bash

set -e

# Some build steps require username, so give them one
export USER=jenkins
export HOME=/home/h2oai
export GRADLE_OPTS='-Dorg.gradle.daemon=false'

echo "###### Activate virtualenv ######"
. /envs/h2o_env_python3.5/bin/activate

echo "###### Clone H2O-3 ######"
git clone https://github.com/h2oai/h2o-3 .

echo "###### Build H2O-3 ######"
make -f docker/Makefile.jenkins build-h2o-3
